/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AutorIdRouteImport } from './routes/autor.$id'
import { Route as EscribirIdRouteImport } from './routes/escribir.$id'
import { Route as ObraIdRouteImport } from './routes/obra.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorIdRoute = AutorIdRouteImport.update({
  id: '/autor/$id',
  path: '/autor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EscribirIdRoute = EscribirIdRouteImport.update({
  id: '/escribir/$id',
  path: '/escribir/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRoute = ObraIdRouteImport.update({
  id: '/obra/$id',
  path: '/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/perfil': typeof PerfilRoute
  '/autor/$id': typeof AutorIdRoute
  '/escribir/$id': typeof EscribirIdRoute
  '/obra/$id': typeof ObraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/perfil': typeof PerfilRoute
  '/autor/$id': typeof AutorIdRoute
  '/escribir/$id': typeof EscribirIdRoute
  '/obra/$id': typeof ObraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/perfil': typeof PerfilRoute
  '/autor/$id': typeof AutorIdRoute
  '/escribir/$id': typeof EscribirIdRoute
  '/obra/$id': typeof ObraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/entrar' | '/perfil' | '/autor/$id' | '/escribir/$id' | '/obra/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entrar' | '/perfil' | '/autor/$id' | '/escribir/$id' | '/obra/$id'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/perfil'
    | '/autor/$id'
    | '/escribir/$id'
    | '/obra/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  PerfilRoute: typeof PerfilRoute
  AutorIdRoute: typeof AutorIdRoute
  EscribirIdRoute: typeof EscribirIdRoute
  ObraIdRoute: typeof ObraIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$id': {
      id: '/autor/$id'
      path: '/autor/$id'
      fullPath: '/autor/$id'
      preLoaderRoute: typeof AutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escribir/$id': {
      id: '/escribir/$id'
      path: '/escribir/$id'
      fullPath: '/escribir/$id'
      preLoaderRoute: typeof EscribirIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$id': {
      id: '/obra/$id'
      path: '/obra/$id'
      fullPath: '/obra/$id'
      preLoaderRoute: typeof ObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  PerfilRoute: PerfilRoute,
  AutorIdRoute: AutorIdRoute,
  EscribirIdRoute: EscribirIdRoute,
  ObraIdRoute: ObraIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
